swagger: '2.0'

info:
    version: v1
    title: Instant decision API
    description: API de decisão instantânea

paths:
  /Rules:
    get:
      tags:
        - Rules
      summary: Listagem de regras
      produces:
        - application/json
      parameters:
        - name: pageNumber
          description: Número da página
          in: query
          required: true
          type: integer
        - name: pageSize
          description: Quantidade de registros na página
          in: query
          required: true
          type: integer
        - name: search
          description: Conteúdo da busca
          in: query
          required: false
          type: string
        - name: initialDate
          description: Data inicial do range de data (format= dateTime)
          in: query
          required: false
          type: string
          format: date-time
        - name: finalDate
          description: Data final do range de data (format= dateTime)
          in: query
          required: false
          type: string
          format: date-time
        - name: sortAsc
          description: Ordenação ascendente
          in: query
          required: false
          type: string
          enum:
              - name
              - lastEdition
              - version
              - statusCode
              - editor
        - name: sortDesc
          description: Ordenação descendente
          in: query
          required: false
          type: string
          enum:
              - name
              - lastEdition
              - version
              - statusCode
              - editor
      responses:
          '200':
              description: Lista com as regras correspondentes aos filtros
              schema:
                $ref: '#/definitions/Rules.ListResponse'
    post:
      tags:
        - Rules
      summary: Inclusão de regras
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          description: Regra a ser criada
          in: body
          required: true
          schema:
              $ref: '#/definitions/Rules.PostBody'
      responses:
        '200':
          description: 'Rule criada'
          schema:
            $ref: '#/definitions/Rules.PostResponse'
    put:
      tags:
        - Rules
      summary: Alteração de regras
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          description: Regra a ser alterada
          in: body
          required: true
          schema:
              $ref: '#/definitions/Rules.PutBody'
      responses:
        '200':
          description: 'Rule alterada'
          schema:
            $ref: '#/definitions/Rules.PostResponse'
  /Rules/{ruleId}:
    get:
      tags:
        - Rules
      summary: Detalhes de uma determinada regra
      produces:
        - application/json
      parameters:
        - in: path
          name: ruleId
          description: Identificador da regra (format= Guid)
          required: true
          type: string
          format: Guid
      responses:
          '200':
            description: 'Detalhes de uma determinada regra'
            schema:
              $ref: '#/definitions/Rules.DetailResponse'
  /Rules/{ruleVersionId}/Preview:
    get:
      tags:
        - Rules
      summary: Preview de uma determinada regra
      produces:
        - application/json
      parameters:
        - in: path
          name: ruleVersionId
          description: Identificador da versão da regra (format= Guid)
          required: true
          type: string
          format: Guid
      responses:
          '200':
            description: Preview de uma determinada versão de regra
            schema:
                $ref: '#/definitions/Rules.PreviewResponse'
  /Rules/{ruleId}/Version:
    get:
      tags:
        - Rules
      summary: Versões de uma determinada regra
      produces:
        - application/json
      parameters:
        - name: ruleId
          in: path
          description: Identificador da regra (format= Guid)
          required: true
          type: string
          format: Guid
        - name: pageNumber
          description: Número da página
          in: query
          required: true
          type: integer
        - name: pageSize
          description: Quantidade de registros na página
          in: query
          required: true
          type: integer
        - name: sortAsc
          description: Ordenação ascendente
          in: query
          required: false
          type: string
          enum:
              - version
              - editorUserName
              - updatedDateUtc
        - name: sortDesc
          description: Ordenação descendente
          in: query
          required: false
          type: string
          enum:
              - version
              - editorUserName
              - updatedDateUtc
      responses:
          '200':
            description: Versões de uma determinada regra
            schema:
                $ref: '#/definitions/Rules.VersionResponse'
  /Rules/{ruleId}/Orchestrator/Entities:
    get:
      tags:
        - Rules
      summary: 'Recupera a listagem de Orquestratores com suas entidades vinculadas filtradas por uma Rule'
      produces:
        - application/json
      parameters:
        - in: path
          name: ruleId
          description: Identificador da regra (format= Guid)
          required: true
          type: string
          format: Guid
      responses:
          '200':
            description: Lista dos orquestradores com as suas entidades de uma determinada regra
            schema:
              $ref: '#/definitions/Rules.OrchestratorEntitites.Response'
  /Rules/UpdateChain:
    post:
      tags:
        - Rules
      summary: Atualizar Rule com orquestradores em cascata
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          description: Regra a ser alterada
          in: body
          required: true
          schema:
              $ref: '#/definitions/Rules.UpdateChainPostBody'
      responses:
        '200':
          description: 'Rule alterada'
          schema:
            $ref: '#/definitions/Rules.UpdateChainPostResponse'

definitions:
  Rules.Dependencies:
    type: object
    properties:
      source:
        type: integer
        enum:
          - 0
          - 1
          - 2
      outputId:
        type: string
      alias:
        type: string
  Rules.FieldDependencies:
    type: object
    properties:
      Id:
        type: string
      alias:
        type: string
      name:
        type: string
      description:
        type: string
  Rules.FeatureDependencies:
    type: object
    properties:
      Id:
        type: string
      alias:
        type: string
      name:
        type: string
      description:
        type: string
      version:
        type: string
      variable:
        type: string
  Rules.ModelDependencies:
    type: object
    properties:
      Id:
        type: string
      alias:
        type: string
      name:
        type: string
      description:
        type: string
      version:
        type: string
      variable:
        type: string
  Rules.RuleDependencies:
    type: object
    properties:
      Id:
        type: string
      alias:
        type: string
      name:
        type: string
      description:
        type: string
      version:
        type: string
      variable:
        type: string
      type:
        type: string
  Rules.Entities:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        format: Guid
      name:
        type: string
  Rules.ListResponse:
      description: Listagem de regras para a tabela
      type: object
      required:
          - pageNumber
          - pageSize
          - totalPages
          - totalRecords
          - data
      properties:
          pageNumber:
              description: Número da página
              type: integer
          pageSize:
              description: Quantidade de registros da página
              type: integer
          totalPages:
              description: Quantidade de páginas
              type: integer
          totalRecords:
              description: Quantidade de registros
              type: integer
          data:
              description: Regras
              type: array
              items:
                  description: Regras
                  type: object
                  required:
                      - id
                      - name
                      - version
                      - statusId
                      - statusCode
                      - lastUpdateUserId
                      - lastUpdateUserName
                      - lastUpdatedDateUtc
                      - latestVersionId
                  properties:
                      id:
                          description: Id da regra (format= Guid)
                          type: string
                          format: Guid
                      name:
                          description: Nome da regra
                          type: string
                      version:
                          description: Versão da regra
                          type: string
                      statusId:
                          description: Id do Status da regra
                          type: integer
                      statusCode:
                          description: Status da regra
                          type: string
                          maxLength: 3
                          minLength: 3
                      lastUpdateUserId:
                          description: Id do último usuário que alterou a regra
                          type: string
                      lastUpdateUserName:
                          description: Nome e sobrenome do último usuário que alterou a regra
                          type: string
                      lastUpdatedDateUtc:
                          description: Data de última alteração da regra (format= dateTime)
                          type: string
                          format: date-time
                      latestVersionId:
                          description: Id da última alteração da regra (format= Guid)
                          type: string
                          format: Guid
  Rules.DetailResponse:
    type: object
    description: 'Detalhes de uma determinada regra'
    required:
      - id
      - key
      - version
      - versionId
      - name
      - lastUpdateUserId
      - lastUpdateUserName
      - lastUpdatedDateUtc
      - statusId
      - statusCode
      - rulesJson
    properties:
      id:
        description: Id da regra (format= Guid)
        type: string
        format: Guid
      key:
        description: Chave da regra
        type: string
      version:
        description: Versão da regra
        type: string
      versionId:
        description: Id da versão da regra (format= Guid)
        type: string
        format: Guid
      name:
        description: Nome da regra
        type: string
      description:
        description: Descrição da regra
        type: string
      dependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.Dependencies'
      lastUpdateUserId:
        description: Id do último usuário que alterou a regra
        type: string
      lastUpdateUserName:
        description: Nome e sobrenome do último usuário que alterou a regra
        type: string
      lastUpdatedDateUtc:
        description: Data de última alteração da regra (format= dateTime)
        type: string
        format: date-time
      statusId:
        description: Status da regra
        type: integer
      statusCode:
        description: Código do status da regra
        type: string
        maxLength: 3
        minLength: 3
      rulesJson:
        type: string
  Rules.PreviewResponse:
      description: Preview de uma determinada regra
      type: object
      required:
        - id
        - version
        - versionId
        - name
        - lastUpdateUserId
        - lastUpdateUserName
        - lastUpdatedDateUtc
        - statusId
        - statusCode
        - key
      properties:
        id:
          description: Id da regra (format= Guid)
          type: string
          format: Guid
        version:
          description: Versão da regra
          type: string
        versionId:
          description: Id da versão da regra (format= Guid)
          type: string
          format: Guid
        name:
          description: Nome da regra
          type: string
        lastUpdateUserId:
          description: Id do último usuário que alterou a regra
          type: string
        lastUpdateUserName:
          description: Nome e sobrenome do último usuário que alterou a regra
          type: string
        lastUpdatedDateUtc:
          description: Data de última alteração da regra (format= dateTime)
          type: string
          format: date-time
        statusId:
          description: Status da regra
          type: integer
        statusCode:
          description: Código do status da regra
          type: string
          maxLength: 3
          minLength: 3
        key:
          description: Chave da regra
          type: string
        description:
          description: Descrição da regra
          type: string
        dependencies:
          type: array
          items:
            $ref: '#/definitions/Rules.Dependencies'
  Rules.VersionResponse:
      description: Listagem de regras para a tabela
      type: object
      required:
          - pageNumber
          - pageSize
          - totalPages
          - totalRecords
          - data
      properties:
          pageNumber:
              description: Número da página
              type: integer
          pageSize:
              description: Quantidade de registros da página
              type: integer
          totalPages:
              description: Quantidade de páginas
              type: integer
          totalRecords:
              description: Quantidade de registros
              type: integer
          data:
              description: Regras
              type: array
              items:
                  description: Regras
                  type: object
                  required:
                      - id
                      - versionId
                      - version
                      - editorId
                      - editorName
                      - updatedDateUtc
                  properties:
                      id:
                          description: Id da regra (format= Guid)
                          type: string
                          format: Guid
                      versionId:
                          description: Id da versão da regra (format= Guid)
                          type: string
                          format: Guid
                      version:
                          description: Versão da regra
                          type: string
                      editorId:
                          description: Id do usuário que alterou a versão da regra
                          type: string
                      editorName:
                          description: Nome e sobrenome do usuário que alterou a versão da regra
                          type: string
                      updatedDateUtc:
                          description: Data de alteração da versão da regra (format= dateTime)
                          type: string
                          format: date-time
  Rules.PostBody:
    type: object
    required:
      - name
      - FieldDependencies
      - FeatureDependencies
      - ModelDependencies
      - ruleMetStatusCode
      - ruleMetStatusId
      - rulesJson
      - userId
    properties:
      name:
        type: string
        description: 'Nome da regra'
      description:
        type: string
        description: 'Descrição da regra'
      FieldDependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.FieldDependencies'
      FeatureDependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.FeatureDependencies'
      ModelDependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.ModelDependencies'
      ruleMetStatusCode:
        type: string
        maxLength: 3
        minLength: 3
      ruleMetStatusId:
        type: integer
      rulesJson:
        type: string
      userId:
        type: string
        description: 'Usuário que inclui a regra (p. ex.: andre.castro)'
  Rules.PostResponse:
    type: object
    required:
      - id
      - key
      - versionId
      - name
      - dependencies
      - ruleMetStatusCode
      - ruleMetStatusId
      - rulesJson
    properties:
      id:
        type: string
        format: Guid
      key:
        type: string
      versionId:
        type: string
        format: Guid
      name:
        type: string
      description:
        type: string
      dependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.Dependencies'
      ruleMetStatusCode:
        type: string
        maxLength: 3
        minLength: 3
      ruleMetStatusId:
        type: integer
      rulesJson:
        type: string
  Rules.PutBody:
    type: object
    required:
      - id
      - key
      - versionId
      - name
      - FieldDependencies
      - FeatureDependencies
      - ModelDependencies
      - ruleMetStatusCode
      - ruleMetStatusId
      - rulesJson
      - userId
    properties:
      id:
        type: string
        format: Guid
      key:
        type: string
      versionId:
        type: string
        format: Guid
      name:
        type: string
      description:
        type: string
      FieldDependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.FieldDependencies'
      FeatureDependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.FeatureDependencies'
      ModelDependencies:
        type: array
        items:
          $ref: '#/definitions/Rules.ModelDependencies'
      ruleMetStatusCode:
        type: string
        maxLength: 3
        minLength: 3
      ruleMetStatusId:
        type: integer
      rulesJson:
        type: string
      userId:
        type: string
  Rules.OrchestratorEntitites.Response:
    type: object
    required:
      - id
      - name
      - entities
    properties:
      id:
        type: string
        format: Guid
      name:
        type: string
      entities:
        type: array
        items:
          $ref: '#/definitions/Rules.Entities'
  Rules.Orchestrators:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        format: Guid
  Rules.UpdateChainPostBody:
    type: object
    required:
      - id
      - versionId
      - orchestrators
    properties:
      id:
        type: string
        format: Guid
      versionId:
        type: string
        format: Guid
      reason:
        type: string
      orchestrators:
        type: array
        items:
          $ref: '#/definitions/Rules.Orchestrators'
  Rules.UpdateChainPostResponse:
    type: object
    required:
      - id
      - name
      - orchestrators
    properties:
      id:
        type: string
        format: Guid
      name:
        type: string
      orchestrators:
        type: array
        items:
          $ref: '#/definitions/Rules.Orchestrators'